stages:
  - openMr


openMr:
    before_script: []   # We do not need any setup work, let's remove the global one (if any)
    stage: openMr
    # only:
    #   - /^feature\/*/   # We have a very strict naming convention
    script:
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID} PRIVATE_TOKEN=${PRIVATE_TOKEN} ./utils/commit.sh # The name of the script