before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
stages:
  - openMr


openMr:
    before_script:
      - apk update && apk add git

    stage: openMr

    script:
        - echo 'hai.............'
        - git version
        - git remote set-url origin https://BadhushaBava:gitlab@438@gitlab.com/myrepo18/SampleProject.git/
        - git push origin HEAD:temp -o merge_request.create -o merge_request.target=master