before_script:
  - apt-get update && apt-get install
  - apt install git-all
stages:
  - createMR


create_merge_request:
  stage: createMR
  tags:
    - autoMR
  script:
    - 'echo Merge request opened by $GITLAB_USER_NAME '
    - ~/temp/commit.sh