before_script:
  - apk add --update curl && rm -rf /var/cache/apk/*
stages:
  - openMr


openMr:
    before_script:
      - apk update && apk add git

    stage: openMr

    script:
    - echo "auto merge requestb stage..........."
    - 'echo Merge request opened by $GITLAB_USER_NAME '
    - chmod +x ${CI_PROJECT_DIR}/commit.sh
    - ./${CI_PROJECT_DIR}/commit.sh