before_script:
  - sudo apt-get install git
stages:
  - createMR


create_merge_request:
  stage: createMR
  script:
    - 'echo Merge request opened by $GITLAB_USER_NAME '
    - git version
    - git push origin HEAD:temp -o merge_request.create -o merge_request.target=master 